packages:
  - 'packages/@fluentui-vue/file-type-icons'
  - 'packages/@fluentui-vue/icons'
  - 'packages/@fluentui-vue/next'
  - 'packages/@fluentui-vue/theme'
  - 'packages/@fluentui-vue/utilities'
  - 'packages/@fluentui-vue/style-utilities'
  - 'packages/@fluentui-vue/vue-hooks'
